name: CI
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
jobs:
  build:
    name: Ruby ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '2.7', '3.0', '3.1', '3.2', '3.3' ]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1.190.0
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake test
