name: CI
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
jobs:
  build:
    name: Ruby ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '2.7', '3.0', '3.1', '3.2', '3.3' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake test
