name: CI
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
jobs:
  build:
    name: Ruby ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '2.7', '3.0', '3.1', '3.2', '3.3' ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@efbf473cab83af4468e8606cc33eca9281bb213f # v1.256.0
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake test
